import base64
from PIL import Image
import io

def get_base64_image(image_path, size=(256, 256)):
    """Converts a local image into a Base64 string for HTML embedding."""
    try:
        img = Image.open(image_path)
        img.thumbnail(size, Image.Resampling.LANCZOS) 
        buffered = io.BytesIO()
        img.save(buffered, format="JPEG", quality=85) 
        img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")
        return f"data:image/jpeg;base64,{img_str}"
    except Exception as e:
        print(f"Error loading {image_path}: {e}")
        return ""

#Function generated by Gemini-3.1
def generate_html_plot(df, x_col, y_col):
    """Generates an interactive zooming/panning HTML string plotting images on a bounded 2D CSS grid with counter-scaling."""
    if df.empty:
        return "<div style='padding: 20px; text-align: center; color: #d1d5db;'>No data to display. Please build the index.</div>"

    #Grab the raw min and max scores
    x_orig_min, x_orig_max = df[x_col].min(), df[x_col].max()
    y_orig_min, y_orig_max = df[y_col].min(), df[y_col].max()

    # Prevent division by zero if all scores happen to be identical
    x_range = (x_orig_max - x_orig_min) if x_orig_max != x_orig_min else 1
    y_range = (y_orig_max - y_orig_min) if y_orig_max != y_orig_min else 1

    #Normalize the raw scores to a clean 0.0 to 1.0 scale
    df[x_col] = (df[x_col] - x_orig_min) / x_range
    df[y_col] = (df[y_col] - y_orig_min) / y_range

    # Inline JavaScript logic with boundary clamping and CSS variable tracking
    js_wheel = "event.preventDefault(); let s = parseFloat(this.getAttribute('data-s')) || 1; let x = parseFloat(this.getAttribute('data-x')) || 0; let y = parseFloat(this.getAttribute('data-y')) || 0; let rect = this.getBoundingClientRect(); let mx = event.clientX - rect.left; let my = event.clientY - rect.top; let z = Math.exp((event.deltaY < 0 ? 1 : -1) * 0.1); let ns = Math.min(Math.max(1, s * z), 15); x = mx - (mx - x) * (ns / s); y = my - (my - y) * (ns / s); let minX = rect.width * (1 - ns); let minY = rect.height * (1 - ns); x = Math.max(minX, Math.min(0, x)); y = Math.max(minY, Math.min(0, y)); this.setAttribute('data-s', ns); this.setAttribute('data-x', x); this.setAttribute('data-y', y); this.style.setProperty('--s', ns); this.querySelector('.zoom-layer').style.transform = `translate(${x}px, ${y}px) scale(${ns})`;"
    js_mousedown = "this.setAttribute('data-drag', 'true'); let x = parseFloat(this.getAttribute('data-x')) || 0; let y = parseFloat(this.getAttribute('data-y')) || 0; this.setAttribute('data-sx', event.clientX - x); this.setAttribute('data-sy', event.clientY - y); this.style.cursor = 'grabbing';"
    js_mousemove = "if(this.getAttribute('data-drag') === 'true') { let s = parseFloat(this.getAttribute('data-s')) || 1; let rect = this.getBoundingClientRect(); let x = event.clientX - parseFloat(this.getAttribute('data-sx')); let y = event.clientY - parseFloat(this.getAttribute('data-sy')); let minX = rect.width * (1 - s); let minY = rect.height * (1 - s); x = Math.max(minX, Math.min(0, x)); y = Math.max(minY, Math.min(0, y)); this.setAttribute('data-x', x); this.setAttribute('data-y', y); this.querySelector('.zoom-layer').style.transform = `translate(${x}px, ${y}px) scale(${s})`; }"
    js_mouseup = "this.setAttribute('data-drag', 'false'); this.style.cursor = 'grab';"
    js_reset = "let p = this.parentElement; p.setAttribute('data-s', 1); p.setAttribute('data-x', 0); p.setAttribute('data-y', 0); p.style.setProperty('--s', 1); p.querySelector('.zoom-layer').style.transform = `translate(0px, 0px) scale(1)`;"

    # Base HTML container with Zoom Viewport and --s variable
    html = f"""
    <div onwheel="{js_wheel}" onmousedown="{js_mousedown}" onmousemove="{js_mousemove}" onmouseup="{js_mouseup}" onmouseleave="{js_mouseup}" data-s="1" data-x="0" data-y="0" data-drag="false" style="--s: 1; position: relative; width: 100%; height: 75vh; border: 1px solid #374151; border-radius: 8px; background-color: #111827; overflow: hidden; font-family: sans-serif; color: #d1d5db; cursor: grab; touch-action: none;">
        <button onclick="{js_reset}" style="position: absolute; top: 15px; right: 15px; z-index: 20; padding: 6px 12px; background-color: #1f2937; color: #f3f4f6; border: 1px solid #4b5563; border-radius: 6px; font-size: 0.9em; font-weight: bold; cursor: pointer; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.5); transition: background-color 0.2s;" onmouseover="this.style.backgroundColor='#374151';" onmouseout="this.style.backgroundColor='#1f2937';">Reset View</button>
        <div class="zoom-layer" style="position: absolute; width: 100%; height: 100%; transform-origin: 0 0; transform: translate(0px, 0px) scale(1); transition: transform 0.05s linear;">
            <div style="position: absolute; top: 50%; left: 0; right: 0; border-top: 1px dashed #4b5563; z-index: 0;"></div>
            <div style="position: absolute; left: 50%; top: 0; bottom: 0; border-left: 1px dashed #4b5563; z-index: 0;"></div>
            <div style="position: absolute; bottom: 20px; left: 50%; transform: translateX(-50%); font-weight: bold; font-size: 1.1em; z-index: 2; background-color: #111827; padding: 0 10px; border-radius: 4px;">{x_col} &rarr;</div>
            <div style="position: absolute; left: 20px; top: 50%; transform: translateY(-50%) rotate(-90deg); font-weight: bold; font-size: 1.1em; z-index: 2; background-color: #111827; padding: 0 10px; border-radius: 4px;">{y_col} &rarr;</div>
    """

    # Plot each image dynamically
    for index, row in df.iterrows():
        img_path = row['Image']
        x_val = row[x_col]
        y_val = row[y_col]

        # Map to 5% - 95% padding range. 
        x_pct = 5 + (x_val * 90)
        y_pct = 5 + (y_val * 90)

        # Fetch the Base64 image string
        b64_src = get_base64_image(img_path)
        
        if b64_src:
            tooltip_text = f"{x_col}: {x_val:.2f}&#10;{y_col}: {y_val:.2f}&#10;{img_path}"
            
            # The inline styles now use a partial counter-scale: calc((0.5 + 0.5 * var(--s)) / var(--s))
            # The hover effects use a bumped up ratio: calc((2.0 + 0.5 * var(--s)) / var(--s))
            html += f"""
            <img src="{b64_src}" title="{tooltip_text}" 
                 style="position: absolute; left: {x_pct}%; bottom: {y_pct}%; 
                        width: 48px; height: 48px; object-fit: cover;
                        transform: translate(-50%, 50%) scale(calc((0.5 + 0.5 * var(--s)) / var(--s))); border-radius: 6px; 
                        box-shadow: 0 4px 6px -1px rgba(0,0,0,0.5); 
                        transition: transform 0.2s ease, z-index 0s; cursor: crosshair; z-index: 1;" 
                 onmouseover="this.style.transform='translate(-50%, 50%) scale(calc((2.0 + 0.5 * var(--s)) / var(--s)))'; this.style.zIndex=10; this.style.boxShadow='0 10px 15px -3px rgba(0,0,0,0.8)';" 
                 onmouseout="this.style.transform='translate(-50%, 50%) scale(calc((0.5 + 0.5 * var(--s)) / var(--s)))'; this.style.zIndex=1; this.style.boxShadow='0 4px 6px -1px rgba(0,0,0,0.5)';">
            """
    html += """
        </div>
    </div>
    """
    return html